### ISSUE TITLE
nextquestion returns two QIDs

### ISSUE THREAD

**Issue by wall0159** [gardners/surveysystem#1]
when running the ./surveycli nextquestion, it returns two IDs
1
2

to replicate:
```
SESSIONID=`SURVEY_HOME=. ./surveycli newsession foo`
export SURVEY_HOME=.
./surveycli addanswer ${SESSIONID} '1:ANS:2:100:200:1200:1300:8:4'
./surveycli nextquestion ${SESSIONID}

```
I think it should return only one?
Cheers, Angus

**Comment by gardners** [comment]
nextquestion returns exactly the list of questionids that the python returns to it.
If there is no python, then the default nextquestion implementation in C will return a list of ALL currently unanswered questions, which might explain the behaviour you are seeing.

**Comment by gardners** [comment]
The case where the question list is being provided from the C get_next_questions_generic() function is covered by backend/src/sequencedanswering.test.
For python, it is not yet covered, as the test framework needs to be extended to allow the creation of python functions.

**Comment by gardners** [comment]
Test cases for the backend can now use python as of commit d580d1a0885d226ffcb12ddbd1b19d3f0423ef28

**Comment by gardners** [comment]
See backend/tests/nextquestionpython.test for an example.
That example provides an answer, and then asks exactly one question in reply, confirming the problem you are seeing does not appear to be a systemic issue.

**Comment by gardners** [comment]
Note to self: Write a test that has > 3 questions, and goes through answering at least two, and making sure it only gets 1 next question provided from a simple python script that returns the first unanswered question.

**Comment by gardners** [comment]
This is tested in tests/sequencedanswering.test.
Currently believed to not be a problem in the backend, but perhaps a hiccup in the python. Create new issue if not.
