### ISSUE TITLE
incoherent state in the survey 

### ISSUE THREAD

**Issue by Yourgene** [gardners/surveysystem#10]
The function getCurrentPage() was like this before : 
```
getCurrentPage(){

        return this.state.survey.currentPage
    }
```
It uses the API from surveyjs, but it sometimes (when you press previous button) returns an outdated page, making the survey bug.

I replaced the function by this : 
```
getCurrentPage(){

        return this.pages[this.stepID-1]
    }
```
It works well now, but it is harder to read. It is more relevant to use the first solution (but it is bugged for the moment)

I dont know why the wrong page is returned : 

- if it is a bug in the front code, it means that other functions can be affected and make the code bug

- if it is a bug in surveyjs, it is less problematic that the first case.

TODO : investigate to know why wrong data is returned when accessing the state of the component sometimes

**Comment by RoboSparrow** [comment]
maybe safer to hook into the transition event:

https://surveyjs.io/Documentation/Library/?id=surveymodel#onCurrentPageChanged

>The event is fired when another page becomes the current. Typically  it happens when a user click on 'Next' or 'Prev' buttons.  sender the survey object that fires the event  option.oldCurrentPage the previous current/active page  option.newCurrentPage a new current/active page

I don't trust these magic properties. They might work in vanilla SJs but the react wrapper..

**Comment by RoboSparrow** [comment]
closing, handled by `SurveyManager`
