### ISSUE TITLE
backend: full utf-8 support

### ISSUE THREAD

**Issue by RoboSparrow** [gardners/surveysystem#105]
example quotation marks
```
EveryDay:Do you enjoyed your ‘free days’?::MULTICHOICE:-1::-999:999:2:3:Yes,No,I do never have ‘free days’:
```
renders

![utf-8](https://user-images.githubusercontent.com/4016086/51003369-59ecc180-1586-11e9-9836-c3aaf2a866c2.png)

**Comment by RoboSparrow** [comment]
another example, this timenextquestion json
```
{"next_questions": [{"id": "blah", "name": "blah", "title": "", "title_text": "Your responses indicate that you only have a\uFFFF\uFFFFmild hickup", "type": "HIDDEN", "unit": ""}]}
```

seems like we have to sanitize the question dictionary?

**Comment by gardners** [comment]
We need to see how the UTF8 characters are being passed to the back end, and make sure we reverse that process appropriately. Create a failing test, please.

**Comment by RoboSparrow** [comment]
@gardners added `character-encoding.test` (PR #124) with \

fails with 
```
{"next_questions": [{"id": "characterencoding", "name": "characterencoding", "title": "Select one from the \uFFFF\uFFFF\uFFFFfollowing\uFFFF\uFFFF\uFFFF", "description": "Description for \uFFFF\uFFFF\uFFFFfollowing\uFFFF\uFFFF\uFFFF", "type": "SINGLECHOICE", "choices": ["`31`", "`42`"], "unit": ""}]}
```

**Comment by gardners** [comment]
Looks to be caused by this bug in kgci:

https://github.com/kristapsdz/kcgi/issues/56
