### ISSUE TITLE
Test case with python bug passes

### ISSUE THREAD

**Issue by wall0159** [gardners/surveysystem#11]
test 002_shouldFAIL_pythonIndentError.test has a python indentation error on line 28, but the test still passes. I think it should fail.

Note that it doesn't need to be an indentation error -- other syntax errors in the python are silently passed

**Comment by gardners** [comment]
The log from the backend indeed shows the failure:

```
2018/10/14.20:58.51:src/errorlog.c:54:remember_error():LOG_ERROR : Using PyImport_GetModule() didn't work either
2018/10/14.20:58.51:src/errorlog.c:54:remember_error():LOG_ERROR : PyRun_SimpleString returned -1 when processing 646 bytes of python
2018/10/14.20:58.51:src/errorlog.c:54:remember_error():LOG_ERROR : Using module __main__ with manually loaded python functions instead of import nextquestion.
2018/10/14.20:58.51:src/errorlog.c:54:remember_error():LOG_ERROR : Searching for python function 'nextquestion_001nextquestionpythonActualLogic_e7b0dad867359782e6e1ad3ad1a3c08f707f45a9'
2018/10/14.20:58.51:src/errorlog.c:54:remember_error():LOG_ERROR : Searching for python function 'nextquestion_001nextquestionpythonActualLogic'
2018/10/14.20:58.51:src/errorlog.c:54:remember_error():LOG_ERROR : Searching for python function 'nextquestion'
2018/10/14.20:58.51:src/errorlog.c:54:remember_error():LOG_ERROR : No matching python function for survey '001nextquestionpythonActualLogic/e7b0dad867359782e6e1ad3ad1a3c08f707f45a9'
```

In this case, the default nextquestion_generic function in C is doing the work, because the python code is wonky, thus the test looks fine. If you had logic that didn't do the questions in order, then it should pick it up.

I guess the question is whether it is worth somehow checking the backend logs for python errors if a python function has been provided.

**Comment by gardners** [comment]
Another option would be to try to compile the python file (which might well fix the module loading errors) when the python code is defined, so that we can abort a test if the python code doesn't compile for any reason.

**Comment by gardners** [comment]
Fixed using the above method.
