### ISSUE TITLE
nextquestion doesn't appear to properly form the output when working from python

### ISSUE THREAD

**Issue by wall0159** [gardners/surveysystem#12]
test 001_nextquestionpythonActualLogic.test uses python to select the next question. nextquestion.py returns the ID of the next question to be asked, however the survey system only returns that QID and not the properly formed (full JSON) output.

eg. it returns 'email' when it should return '{"next_questions": [{"id": "email", "name": "email", "title": "How boring was question 1?", "title_text": "How boring was question 1?", "type": "text"}]}'
(lines 47 and 48 in the testfile)

Note that the nextquestion.py can't create this as it doesn't have access to the questions-definitions.

**Comment by gardners** [comment]
The code path is the same, regardless of which source provides the next question(s).
I suspect that the python might not be returning the result exactly correctly, but without the missing python library, it is hard to tell.
We should look at this together in the lab.

**Comment by wall0159** [comment]
Thanks, I'll come and see you next week. 

I've created a test that doesn't depend on the external python library: 003_outputFromPythonShouldBeSameAsFromC.test

**Comment by gardners** [comment]
Assigned to Angus, as next step is no longer dependent on me.
