### ISSUE TITLE
Make it obvious when python nextquestion function can't be run

### ISSUE THREAD

**Issue by RoboSparrow** [gardners/surveysystem#128]
Allow passing on multiple next_questions, see following line and comment in `get_next_questions_generic`
https://github.com/gardners/surveysystem/blob/master/backend/src/nextquestion.c#L407-L408

(I thought I logged that two days ago bust must have forgotten to  press submit)

**Comment by gardners** [comment]
The correct behaviour when falling back to the generic implementation should be to throw a 500 error, not to use this generic implementation, because the generic implementation may expose questions we don't want exposed.

**Comment by gardners** [comment]
Joerg to write a test.

**Comment by gardners** [comment]
The above commit seems to have broken lots of tests, with the "could not load python" message appearing.
