### ISSUE TITLE
backend: http request: return remaining questions count

### ISSUE THREAD

**Issue by RoboSparrow** [gardners/surveysystem#13]
As discussed, it would be good to include a count of the *remaining* questions into the responses of each data submission. This keeps the user informed about the current stage of the survey. 

endpoints:

* `/surveyapi/nextquestion`
* `/surveyapi/newsession`

**Comment by gardners** [comment]
The factors to be considered here are:
1. Only the python code can know how many questions there are to go, or perhaps more generally, what percentage of the survey remains.
2. The percentage remaining can change wildly based on answers provided.

That said, it would be quite easy to add a convention where the Python is expected to return a tuple consisting of a numeric progress indication (0 to 100), as well as the current list of next questions to ask.  We should meet with Angus to discuss this.

**Comment by RoboSparrow** [comment]
@wall0159 just checking in again on this. any progress?

**Comment by RoboSparrow** [comment]
implement this for python-less survey

```c
struct session {
    //...
   int given_answer_count;
   //
}
```
update on *load_session* and *save_session*, include into `free_session`;

**Comment by RoboSparrow** [comment]
frontend: #406
