### ISSUE TITLE
backend should accept a python list of QIDs

### ISSUE THREAD

**Issue by wall0159** [gardners/surveysystem#144]
Hi Paul,
As discussed, the python needs to be able to return multiple IDs to the backend, to signify that multiple questions are to be asked. I've put here that the backend should accept a python list, based on our chat on Friday, but I don't think it _has_ to be that way. I'd also be happy to return a comma/colon/etc delimited string.
Cheers, Angus

**Comment by RoboSparrow** [comment]
closing as invalid, see https://github.com/gardners/surveysystem/commit/a76613ba8845d755d15fd78267bb40904565029c
