### ISSUE TITLE
need interface to python algorithm

### ISSUE THREAD

**Issue by wall0159** [gardners/surveysystem#15]
I think the best bet is to use a similar interface to the nextquestion.py, that the back-end runs and passes a long string of json, a python-dict or whatever to (e.g.) algorithm.py. It can then get the results back and send them to the front end for display.

I don't want the algorithm to return HTML, because the front-end may have very different ways of presenting the data. I think it best if the interface is JSON (partly because that code is already written!). 

I think it will work like this:
1. backend runs algorithm.py, and passes it, as an argument, a JSON string containing all the user's answers with the associated QIDs (perhaps also needs a SESSIONID?) 
2. algorithm.py returns a string which is JSON and contains fields that correspond to useful things to display (currently, this consists of 'diagnoses' and 'recommendations'
3. backend passes this JSON to the front-end, and the front-end presents it to the user in some way. We have a webpage to do this already, which might save quite a bit of front-end dev

Does this sound ok?

**Comment by gardners** [comment]
Almost. For simplicity, the functions should still be in nextquestion.py. We will change the name of the file to something more sensible. Suggestions welcome.

The function can return whatever it likes as a string. It will be upto the front end to interpret it.  You can just return boring HTML for now for testing, if you wish.

I have added a test case for this, and the core functionality.  Commit coming up.

**Comment by gardners** [comment]
I'll close this one now. When we decide on a name for the single python file, we can do that in a separate issue.
