### ISSUE TITLE
questions list should contain human-readable tags

### ISSUE THREAD

**Issue by wall0159** [gardners/surveysystem#2]
nextquestion.py accepts two arguments, questions and answers. Both are python lists.
The questions list is just a list of (numeric) question IDs, and the answers list is a list of dicts, much like JSON. 

I think the question list needs to be a list of dicts as well, and contain the QID and the human-readable tag (column 6 in the survey question csv). I *think* that is all that is needed...  (My calcNextQuestion code refers only to human readable tags because I'd go crazy referring only to IDs! ;-) )

Cheers, Angus

**Comment by gardners** [comment]
As we discussed, use tags instead of numeric IDs, as the system assumes that they are strings, anyway.
