### ISSUE TITLE
frontend: checkbox/radio click area

### ISSUE THREAD

**Issue by wall0159** [gardners/surveysystem#202]
Is it possible to allow people to click on the text not just the radio button? They are a very small target. Also, for the email question, if I type in an email and presses <enter> the question resets to blank. To get to the next question, I must type an email then click 'next question' button

**Comment by RoboSparrow** [comment]
assigning click events outside a standard HTML radio button is not a good idea (accidental clicks/taps)

Either I suggest to make it larger or replace it with buttons

* example: https://bootsnipp.com/snippets/nPxOv

**Comment by RoboSparrow** [comment]
partial;y resolved in https://github.com/gardners/surveysystem/commit/1f0d843e76b05740d685d67da16cb0a6621a84cf#diff-60f6d48dc32a5b017d8b3c0cc5f9fbad

to be replaces with a toggle button solution
