### ISSUE TITLE
Backend is passing front-end a complete list of questions

### ISSUE THREAD

**Issue by wall0159** [gardners/surveysystem#3]
According to Vlad's report, the back-end is passing the front-end a complete list of questions, and then on subsequent questions is passing just the ID of the new question to ask. It's not an immediate priority, but I think we need to change this so that the back-end can pass the front end the details of the current question to ask (only). It's fine to allow both operations (ie. it can pass the complete question list at the start followed by IDs OR it can pass each question one at a time), if that is wanted

**Comment by Yourgene** [comment]
the workflow of the front was changed : now, the back end sends the details (id and content) of the question to the front only when it is needed. Front end doesn't have the list of the questions at the beginning of the survey.

This change was started during commit 0a353968a2b902ccc0d5e8573fd241dfde503f12

**Comment by gardners** [comment]
Solved as described above.
