### ISSUE TITLE
backend doesn't fail when answering non-existent question

### ISSUE THREAD

**Issue by wall0159** [gardners/surveysystem#7]
The backend should return an error if it receives an answer to a question that doesn't exist. eg this code should fail:

echo "Test 4 - non-existent question should cause error"
echo "======"
# build questions-def file
mkdir -p surveys/veryReduced
echo 'version 1' > surveys/veryReduced/current
echo 'Silly test survey updated' >> surveys/veryReduced/current
echo '1:Email Address:Email Address:TEXT: -1:e mail:-999:999:2:0:0:' >> surveys/veryReduced/current
echo '2:Password:Password:TEXT: -1:password1:-999:999:2:0:0:' >> surveys/veryReduced/current
SESSIONID=`SURVEY_HOME=. ./surveycli newsession veryReduced`
echo $SESSIONID
SURVEY_HOME=. ./surveycli addanswer ${SESSIONID}  nonExistentQuestion:ANS:2: 100:200:1200:1300:8:4

(I've introduced some spaces to get rid of github's ridiculous emoticons. 'TEXT: -1' should have the space removed, as should '2: 100' and 'e mail')

**Comment by gardners** [comment]
Resolved.
