### ISSUE TITLE
Answering question 1 should select question 2 as the next question, but returns 0

### ISSUE THREAD

**Issue by wall0159** [gardners/surveysystem#8]
To replicate:

```
echo "Test 2 - question 1 answer should return question 2 (reduced survey)"
echo "======"
```
```
# build questions-def file
mkdir -p surveys/veryReduced
echo 'version 1' > surveys/veryReduced/current
echo 'Silly test survey updated' >> surveys/veryReduced/current
echo '1:Email Address:Email Address:TEXT:-1:email:-999:999:2:0:0:' >> surveys/veryReduced/current
echo '2:Password:Password:TEXT: -1:password1:-999:999:2:0:0:' >> surveys/veryReduced/current
SESSIONID=`SURVEY_HOME=. ./surveycli newsession veryReduced`
echo $SESSIONID
SURVEY_HOME=. ./surveycli addanswer ${SESSIONID}  1:ANS:2:100:200:1200:1300:8:4
SURVEY_HOME=. ./surveycli nextquestion ${SESSIONID}

```
(I've introduced some spaces to get rid of github's ridiculous emoticons. 'TEXT: -1' should have the space removed, as should '2: 100' and 'e mail')

**Comment by wall0159** [comment]
I've looked at this more, and I think it's a bug in my python code

**Comment by Yourgene** [comment]
:warning: not related to the issue : you can get rid of the emojis by wrapping the code with "Insert code" option, while editing your comment.

**Comment by gardners** [comment]
The test framework is now in place, and there is a test, backend/tests/sequencedanswering.test that should test that this works correctly, when using the default C next question logic.  I will soon add support for having a python next question function.

**Comment by gardners** [comment]
Above comment appllies as of commit 73fe57765f6f167fefa0912258990f0a56078956
