### ISSUE TITLE
backend: /fcgi_accesstest fails if test files/test dirs already exist

### ISSUE THREAD

**Issue by RoboSparrow** [gardners/surveysystem#84]
running `curl -i http://localhost:3099/surveyapi/accesstest` more than once once  causes it to fail with
```
500 Could not mkdir path <PATH>/surveysystem/backthisend/surveys/testfile, errno=17 (File exists)
```

I am using this to check deployment.
Also, this is a great health check to run on the frontend

affected:

surveys/testfile
surveys/testdir/testfile
sessions/testfile
sessions/testdir/testfile

**Comment by gardners** [comment]
Write a test that calls accesstest twice to confirm whether the bug has been fixed.

**Comment by gardners** [comment]
accesstest updated to call 2x. All is fine.
