### ISSUE TITLE
backend: free_answer() incomplete?

### ISSUE THREAD

**Issue by RoboSparrow** [gardners/surveysystem#95]
I am not sure, but it looks like freeing the answer is incomplete? Just by comparing struct answer in `include/survey.h` with free_answer() in `src/sessions.c`

current:

```c
void free_answer(struct answer *a)
{
  if (!a) return;

  freez(a->uid);
  freez(a->text);

  free(a);
  return;
}
```

```c
struct answer {
  char *uid;
  long long value;
  char *text;
  long long lat,lon;
  long long time_begin;
  long long time_end;
  int time_zone_delta;
  int dst_delta;
  char *unit;
};
```

**Comment by gardners** [comment]
You will need to add free(a->unit). The others are static fields in the answer structure, so do not need freeing -- free(a) frees them.

**Comment by RoboSparrow** [comment]
@gardners I see, will commit that small change directly, without PR. Frohes Neues Jahr!

**Comment by gardners** [comment]
danke. Guter Rutsch dir auch!
